# Configuração do Cluster Kind
# Define como o cluster Kind mapeia portas do Kubernetes para meu localhost.
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      # Frontend: NodePort 30000 -> localhost:3000 (para acesso no navegador)
      - containerPort: 30000
        hostPort: 3000
        protocol: TCP
