# Deployment e Service do Frontend
# Gerencia a implantação e exposição do meu frontend.

# Deployment do Frontend: 1 pod
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1 # 1 instância do frontend
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: giovanamori/devstage-frontend:latest
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_API # URL do backend que o frontend usará
              value: "http://localhost:5000" # Mapeado pelo Kind

---
# Service do Frontend: Expõe o frontend
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000 # NodePort para acesso externo (mapeado pelo Kind)
  type: NodePort
